### ISSUE TITLE
edt

### ISSUE THREAD

**Issue by salathiel1999** [SistemasTecTlaxiaco/actividad-7-estructura-de-desglose-de-trabajo-edt-dream-team1#1]
[Edt Ihomee.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-estructura-de-desglose-de-trabajo-edt-dream-team1/files/9876126/Edt.Ihomee.pdf)

**Comment by josealfredo79** [comment]
La conclusión es de 12 líneas

**Comment by josealfredo79** [comment]
Calificación 26

**Comment by josealfredo79** [comment]
Bien hecho y revisado
